version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: docker
    directory: /ci
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    commit-message:
      prefix: ci
    groups:
      images:
        patterns: ['*']
