-- termo.api against a live server: one session, one window, one pane.
local api = termo.api

describe("version", function()
	it("is a dotted version string", function()
		eq(type(api.version()), "string")
		eq(api.version():match("^%d+%.%d+") ~= nil, true)
	end)
end)

describe("list", function()
	it("documents every function", function()
		local list = api.list()
		eq(#list, 24)
		for _, f in ipairs(list) do
			eq(type(api[f.name]), "function")
			eq(type(f.signature), "string")
			eq(type(f.doc), "string")
		end
	end)
end)

describe("eval", function()
	it("expands against the current pane by default", function()
		eq(api.eval("#{pane_width}"), "80")
		eq(api.eval("#{window_height}"), "24")
	end)
	it("accepts session, window and pane handles", function()
		eq(api.eval("#{session_name}", "$0"), "0")
		eq(api.eval("#{window_index}", "@0"), "0")
		eq(api.eval("#{pane_id}", "%0"), "%0")
	end)
	it("rejects a bad handle without touching the server", function()
		eq(fails(api.eval, "#{pane_id}", "%77"):match("no such target") ~= nil, true)
		eq(api.eval("#{pane_id}"), "%0")
	end)
end)

describe("options", function()
	it("reads typed values", function()
		eq(api.get_option("history-limit"), 2000)
		eq(api.get_option("renumber-windows"), false)
		eq(api.get_option("mode-keys"), "emacs")
		eq(type(api.get_option("terminal-features")), "table")
	end)
	it("writes through the same parser as set-option", function()
		api.set_option("history-limit", 4321)
		eq(api.get_option("history-limit"), 4321)
		api.set_option("mode-keys", "vi", "@0")
		eq(api.get_option("mode-keys", "@0"), "vi")
		api.set_option("mode-keys", "emacs", "@0")
	end)
	it("rejects bad names and values", function()
		eq(fails(api.get_option, "no-such-option"), "no such option: no-such-option")
		eq(fails(api.set_option, "history-limit", "abc"), "value is invalid: abc")
	end)
end)

describe("print", function()
	it("reaches the client", function()
		print("# print from a spec")
	end)
end)

describe("lists", function()
	it("enumerate sessions, windows and panes with handles", function()
		local sessions = api.list_sessions()
		eq(#sessions, 1)
		eq(sessions[1].id, "$0")
		eq(sessions[1].name, "0")
		eq(sessions[1].windows, 1)
		eq(sessions[1].attached, false)
		local windows = api.list_windows()
		eq(#windows, 1)
		eq(windows[1].id, "@0")
		eq(windows[1].index, 0)
		eq(windows[1].active, true)
		eq(windows[1].panes, 1)
		eq(#api.list_windows("$0"), 1)
		local panes = api.list_panes("@0")
		eq(#panes, 1)
		eq(panes[1].id, "%0")
		eq(panes[1].active, true)
		eq(panes[1].width, 80)
		eq(panes[1].height, 24)
		eq(panes[1].floating, false)
		eq(fails(api.list_windows, "$9"), "no such target: $9")
	end)
end)

describe("fuzzy", function()
	it("scores matches and returns nil otherwise", function()
		eq(type(api.fuzzy("nw", "new-window")), "number")
		eq(api.fuzzy("new", "new-window") > api.fuzzy("nw", "new-window"), true)
		eq(api.fuzzy("zzz", "new-window"), nil)
		eq(api.fuzzy("", "anything"), 0)
		eq(api.fuzzy("a", ""), nil)
	end)
end)
