language = "C"
include_guard = "TERMO_RS_H"
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]
no_includes = true
cpp_compat = false
style = "type"
usize_is_size_t = true

[export]
prefix = "TERMO_RS_"
exclude = [
  "utf8_append",
  "utf8_build_one",
  "utf8_copy",
  "utf8_cstrhas",
  "utf8_cstrwidth",
  "utf8_from_data",
  "utf8_fromcstr",
  "utf8_fromwc",
  "utf8_isvalid",
  "utf8_open",
  "utf8_padcstr",
  "utf8_rpadcstr",
  "utf8_sanitize",
  "utf8_set",
  "utf8_stravis",
  "utf8_stravisx",
  "utf8_strlen",
  "utf8_strvis",
  "utf8_strwidth",
  "utf8_to_data",
  "utf8_tocstr",
  "utf8_towc",
  "utf8_update_width_cache",
  "utf8_has_zwj",
  "utf8_is_zwj",
  "utf8_is_vs",
  "utf8_is_hangul_filler",
  "utf8_should_combine",
  "hanguljamo_check_state",
]

[const]
allow_static_const = true
