-- Writes docs/api.md from termo.api.list(). Runs inside the server:
--
--   tools/gen-api-doc.sh > docs/api.md
--
-- The C tables in src/lua/*.c are the single source of the signatures and
-- one-line docs; the prose below describes what the tables cannot.
local api = termo.api

local groups = {
	{ "Reading state", { "version", "list", "eval", "list_sessions",
	    "list_windows", "list_panes", "get_option", "fuzzy" } },
	{ "Changing state", { "set_option", "cmd", "cmd_async" } },
	{ "Events", { "on", "off", "emit" } },
	{ "Keys", { "keymap_set", "keymap_del" } },
	{ "Time and processes", { "defer", "timer", "system" } },
	{ "Status line", { "format_add" } },
	{ "UI", { "menu", "popup", "message", "prompt" } },
}

local out = {}
local function w(s)
	out[#out + 1] = s
end

w("# termo.api")
w("")
w("Generated by `tools/gen-api-doc.sh` from the tables in `src/lua/*.c`; " ..
    "do not edit by hand.")
w("")
w("`termo.api` is the flat C surface the Lua runtime (`runtime/lua/termo/`) " ..
    "builds on. Handles are tmux ids as strings: `$1` a session, `@2` a " ..
    "window, `%3` a pane. Reading state is evaluating `#{}` formats; " ..
    "changing it is running commands. Every function returns without " ..
    "waiting; one that needs to wait takes a callback.")
w("")
w("## Where commands run")
w("")
w("`cmd(string)` follows the same rule as hooks:")
w("")
w("- inside a running command (a key binding, `run-lua`, `init.lua`, a " ..
    "hook): the commands are queued right after it, in the order of the " ..
    "calls, and nothing is returned;")
w("- inside an event handler or a menu, prompt or popup callback: the " ..
    "commands are queued on the client's queue and run once the core is " ..
    "back in its loop; nothing is returned;")
w("- from a timer or a `system` callback: the commands run now and " ..
    "`output, error` come back. A command that has to wait (`run-shell`, " ..
    "`display-popup`) returns `nil, \"asynchronous command, use " ..
    "cmd_async\"`; when something else is already waiting on the queue the " ..
    "error is `\"command queue busy, use cmd_async\"`.")
w("")
w("`cmd_async(string, fn)` works everywhere and calls `fn(output, error)` " ..
    "when the commands have finished.")
w("")
w("## Budget")
w("")
w("Lua runs inside the server's single event loop. A call from a key, " ..
    "`run-lua` or a timer may take 2 seconds; an event handler or a status " ..
    "line variable 50 milliseconds. Past that the call is cut with an error, " ..
    "reported to the client that caused it or to `show-messages`.")
w("")

local byname = {}
for _, f in ipairs(api.list()) do
	byname[f.name] = f
end
local seen = {}
for _, group in ipairs(groups) do
	w("## " .. group[1])
	w("")
	for _, name in ipairs(group[2]) do
		local f = byname[name]
		if f == nil then
			error("no such function in termo.api: " .. name)
		end
		seen[name] = true
		w("### `termo.api." .. f.name .. "`")
		w("")
		w("```lua")
		w(f.signature)
		w("```")
		w("")
		w(f.doc:sub(1, 1):upper() .. f.doc:sub(2) .. ".")
		w("")
	end
end
for _, f in ipairs(api.list()) do
	if not seen[f.name] then
		error("function not in a documentation group: " .. f.name)
	end
end

w("## The Lua side")
w("")
w("`init.lua` (`runtime/lua/termo/init.lua`) exposes the same functions " ..
    "as `termo.cmd`, `termo.on` and so on, plus:")
w("")
w("- `termo.keymap.set(key, rhs)`, `set(table, key, rhs, opts)`, `del`, " ..
    "`root(key, rhs)`;")
w("- `termo.opt.name` reads and writes options, underscores standing for " ..
    "dashes; `termo.opt.of(handle)` for a session, window or pane;")
w("- `termo.ui.menu`, `popup`, `message(fmt, ...)`, `prompt`, " ..
    "`confirm(question, fn)`;")
w("- `termo.format.add(name, fn)` and `del(name)`;")
w("- `termo.json.encode` and `decode`;")
w("- `termo.layout.apply(spec, {target, done})` for declarative splits;")
w("- `termo.hints.mode(name, spec)` and `setup()` for modal key tables " ..
    "with a hint bar;")
w("- `termo.palette.add`, `open`, `setup{key}` for a fuzzy command palette;")
w("- `termo.float.new`, `toggle`, `move`, `setup{keys}` for floating panes;")
w("- `termo.pack.setup{...}`, `load(dir)`, `update()`, `list()` for plugins " ..
    "with a `termo.json` manifest.")
w("")
w("`run-lua -j 'return termo.api.list_panes()'` prints JSON, which is how " ..
    "other languages use the same API from outside the server.")

return table.concat(out, "\n")
