#!/usr/bin/env python3
"""Record where the C module's width source and unicode-width disagree.

  tools/width-delta.py [--build build] [--out docs/width-delta.md]

Builds two probes, one against the width function the C module uses on this
host (utf8proc_charwidth when utf8proc is installed, wcwidth otherwise) and
one against the vendored unicode-width crate, applies each module's rules and
writes the differing ranges as a Markdown table.
"""

from __future__ import annotations

import argparse
import platform
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAST = 0x10FFFF

C_PROBE = r"""
#include <locale.h>
#include <stdio.h>
#include <wchar.h>
#ifdef HAVE_UTF8PROC
#include <utf8proc.h>
#endif
int main(void)
{
	long c;
	if (setlocale(LC_CTYPE, "en_US.UTF-8") == NULL)
		setlocale(LC_CTYPE, "C.UTF-8");
#ifdef HAVE_UTF8PROC
	fprintf(stderr, "utf8proc %s\n", utf8proc_version());
#else
	fprintf(stderr, "wcwidth %s\n", setlocale(LC_CTYPE, NULL));
#endif
	for (c = 0; c <= 0x10ffff; c++) {
#ifdef HAVE_UTF8PROC
		int w = utf8proc_charwidth(c);
#else
		int w = wcwidth(c);
#endif
		putchar((unsigned char)w);
	}
	return 0;
}
"""

RS_PROBE = r"""
use std::io::Write;
use unicode_width::UnicodeWidthChar;
fn main() {
    let v = unicode_width::UNICODE_VERSION;
    eprintln!("unicode-width {}.{}.{}", v.0, v.1, v.2);
    let mut out = Vec::with_capacity(0x110000);
    for c in 0..=0x10ffffu32 {
        let w = char::from_u32(c).map_or(-2i8, |ch| ch.width().map_or(-1, |w| w as i8));
        out.push(w as u8);
    }
    std::io::stdout().write_all(&out).unwrap();
}
"""

TABLE = ROOT / "src" / "rs" / "utf8" / "width.rs"


def default_table() -> set[int]:
    codepoints = set()
    for line in TABLE.read_text().splitlines():
        line = line.strip()
        if line.startswith("(0x") and line.endswith("),"):
            codepoints.add(int(line[1:].split(",")[0], 16))
    return codepoints


def build_c(tmp: Path) -> tuple[bytes, str]:
    src = tmp / "probe.c"
    src.write_text(C_PROBE)
    flags = []
    for name in ("libutf8proc", "utf8proc"):
        r = subprocess.run(["pkg-config", "--cflags", "--libs", name], capture_output=True, text=True)
        if r.returncode == 0:
            flags = ["-DHAVE_UTF8PROC"] + r.stdout.split()
            break
    subprocess.run(["cc", "-O2", str(src), "-o", str(tmp / "probe-c")] + flags, check=True)
    r = subprocess.run([str(tmp / "probe-c")], capture_output=True, check=True)
    return r.stdout, r.stderr.decode().strip()


def build_rs(tmp: Path, build: Path) -> tuple[bytes, str]:
    rlibs = sorted(build.glob("subprojects/unicode-width-*/libunicode_width.rlib"))
    if not rlibs:
        sys.exit(f"no libunicode_width.rlib under {build}/subprojects; run ninja first")
    src = tmp / "probe.rs"
    src.write_text(RS_PROBE)
    subprocess.run(["rustc", "--edition", "2021", "-O", "--extern", f"unicode_width={rlibs[0]}",
                    str(src), "-o", str(tmp / "probe-rs")], check=True)
    r = subprocess.run([str(tmp / "probe-rs")], capture_output=True, check=True)
    return r.stdout, r.stderr.decode().strip()


def c_effective(raw: int) -> int | None:
    w = raw - 256 if raw > 127 else raw
    if w < 0:
        return None
    return w


def rs_effective(cp: int, raw: int) -> int | None:
    w = raw - 256 if raw > 127 else raw
    if w == -2:
        return None
    if 0x80 <= cp <= 0x9F:
        return 0
    if w < 0:
        return 1
    return min(w, 2)


def ranges(c: bytes, r: bytes, table: set[int]):
    start = None
    key = None
    for cp in range(LAST + 1):
        if 0xD800 <= cp <= 0xDFFF or cp in table:
            k = None
        else:
            cw, rw = c_effective(c[cp]), rs_effective(cp, r[cp])
            k = None if cw == rw else (cw, rw)
        if k != key:
            if key is not None:
                yield start, cp - 1, key
            start, key = cp, k
    if key is not None:
        yield start, LAST, key


def fmt(w: int | None) -> str:
    return "error" if w is None else str(w)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--build", default=str(ROOT / "build"))
    p.add_argument("--out", default=str(ROOT / "docs" / "width-delta.md"))
    args = p.parse_args()
    with tempfile.TemporaryDirectory(prefix="termo-width-") as tmp:
        c, c_name = build_c(Path(tmp))
        r, r_name = build_rs(Path(tmp), Path(args.build))
    rows = list(ranges(c, r, default_table()))
    total = sum(hi - lo + 1 for lo, hi, _ in rows)
    lines = [
        "# Width delta: C module versus Rust module",
        "",
        f"Generated by `tools/width-delta.py` on {platform.system()} {platform.machine()} "
        f"against `{c_name}` (the C module's source on this host, `utf8_width` in "
        f"`src/utf8/utf8.c`) and `{r_name}` (`Widths::width` in `src/rs/utf8/width.rs`: "
        "C1 controls are 0, controls unicode-width declines are 1, wider than 2 is 2). "
        "The 160-entry default table overrides both and is left out. Each row is a range "
        "of codepoints where the two modules give a different width to a cell; `error` "
        "is the C module refusing the character (`UTF8_ERROR` from `utf8_append`).",
        "",
        f"Codepoints that differ: {total} in {len(rows)} ranges.",
        "",
        "| Range | C | Rust | Count |",
        "|---|---|---|---|",
    ]
    for lo, hi, (cw, rw) in rows:
        span = f"U+{lo:04X}" if lo == hi else f"U+{lo:04X}..U+{hi:04X}"
        lines.append(f"| {span} | {fmt(cw)} | {fmt(rw)} | {hi - lo + 1} |")
    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}: {total} codepoints in {len(rows)} ranges")
    return 0


if __name__ == "__main__":
    sys.exit(main())
